### PR TITLE
Content for Ecosystem Section

### PR DESCRIPTION
**Pull request by ranjanan**

### CODE REVIEW

**Comment by ranjanan** [comment]
cc: @ViralBShah

**Comment by ChrisRackauckas** [comment]
Oh, and the Lorenz animation would be great for the scientific computing tab. The visualization tab should get something more data visualization related.

**Comment by ViralBShah** [comment]
Yes, everything is pretty haphazardly chosen. I will make one more pass over it. There will be no significant changes before it goes live except for a few changes for choices of organizations and text edits.

The website will go live after 0.7, but before 1.0.

**Comment by ViralBShah** [comment]
The main thing is that all the tabs need to be as inclusive as can be without cluttering things, and advertise well maintained packages.

**Pull request merged**
